const express = require("express");
const { authentication } = require("../auth/authUtil");
const router = express.Router();
router.use("/v1/auth", require("./access/index"));
router.use("/v1/test", require("./test/index"));
router.use(authentication);
router.use("/v1/question", require("./question/index"));
router.use("/v1/comment", require("./nestedComment/index"));
router.use("/v1/vote", require("./vote/index"));
module.exports = router;
