const express = require("express");
const { authentication } = require("../auth/authUtil");
const loggerMiddleware = require("../middlewares/logger.middleware");
const router = express.Router();
router.use(loggerMiddleware());
router.use("/v1/auth", require("./access/index"));
router.use("/v1/test", require("./test/index"));
router.use(authentication);
router.use("/v1/question", require("./question/index"));
router.use("/v1/comment", require("./nestedComment/index"));
router.use("/v1/vote", require("./vote/index"));
router.use("/v1/profile", require("./userProfile/index"));
router.use("/v1/upload", require("./upload/index"));
router.use("/v1/follow", require("./follow/index"));
router.use("/v1/chat", require("./chat/index"));
router.use("/v1/notification", require("./notification/index"));
module.exports = router;
